name: Deploy Streamlit Dashboard

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    environment: prod
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create .env file with AWS credentials
        shell: bash
        run: |
          cat > .env << 'ENVEOF'
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
          S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          ENVEOF
          chmod 600 .env
          
      - name: Stop existing containers
        shell: bash
        run: |
          docker-compose down --remove-orphans || true
      
      - name: Build and start containers
        shell: bash
        run: |
          docker-compose up -d --build
      
      - name: Wait for container to be healthy
        shell: bash
        run: |
          sleep 10
          docker-compose ps
      
      - name: Show container logs
        shell: bash
        run: |
          docker logs music_dashboard --tail 50 || true
      
      - name: Verify deployment
        shell: bash
        run: |
          curl -f http://localhost:8502 || echo "Warning: App might not be ready yet"
